dummy:
  name: 'poc'

service_account: dev-pipeline.json

logger:
  use: default
  config:

    version: 1

    formatters:
      default:
        format: 'LOADED FROM GS {app_name} %(levelname)9s %(asctime)3s Module:  %(message)s'

    handlers:
      default:
        level: 'INFO'
        formatter: 'default'
        class: 'logging.StreamHandler'
        stream: 'ext://sys.stdout' # Default is stderr

      errors:
        level: 'ERROR'
        formatter: 'default'
        class: 'logging.StreamHandler'

    loggers:
      default:
        handlers: ['default', 'errors']
        level: 'INFO'
        propagate: no


